export const imageSources = [
    { src: "./Images/Library(3).jpg", desc: "Calm and Inviting Ambiance" },
    { src: "./Images/Library(4).jpg", desc: "Spacious and Modern Interior" },
    { src: "./Images/Library(5).jpg", desc: "A Quiet Place for Study" },
    { src: "./Images/Library(6).jpg", desc: "Peaceful Reading Nooks" },
    { src: "./Images/Library(7).jpg", desc: "Natural Lighting and Greenery" },
    { src: "./Images/Library(8).jpg", desc: "Modern and Elegant Design" },
    { src: "./Images/Library(9).jpg", desc: "Comfortable Seating" },
    { src: "./Images/Library(10).jpg", desc: "Wide Collection of Books" },
    { src: "./Images/Library(11).jpg", desc: "Quiet Study Zones" },
    { src: "./Images/Library(12).jpg", desc: "Relaxing Ambiance" },
    { src: "./Images/Library(13).jpg", desc: "Beautiful Architecture" },
    { src: "./Images/Library(14).jpg", desc: "Bookshelf in the Corner" },
    { src: "./Images/Library(15).jpg", desc: "Modern Furniture and Style" },
    { src: "./Images/Library(16).jpg", desc: "Great for Group Studies" },
    { src: "./Images/Library(17).jpg", desc: "Inspiring Library Views" },
    { src: "./Images/Library(18).jpg", desc: "Natural Vibes with Large Windows" },
    { src: "./Images/Library(19).jpg", desc: "Cozy and Quiet Spaces" },
    { src: "./Images/Library(20).jpg", desc: "Elegant Library Lighting" },
    { src: "./Images/Library(21).jpg", desc: "Innovative and Modern Spaces" },
    { src: "./Images/Library(22).jpg", desc: "Bright and Open Layout" },
    { src: "./Images/Library(23).jpg", desc: "Space for Individual Study" },
    { src: "./Images/Library(24).jpg", desc: "Comfortable Lounge Areas" },
    { src: "./Images/Library(25).jpg", desc: "Perfect for Studying and Reading" },
    { src: "./Images/Library(26).jpg", desc: "Peaceful and Calm Environment" },
    { src: "./Images/Library(27).jpg", desc: "Warm Lighting and Relaxing Spaces" },
    { src: "./Images/Library(28).jpg", desc: "Plenty of Natural Light" },
    { src: "./Images/Library(29).jpg", desc: "Library with a View" },
    { src: "./Images/Library(30).jpg", desc: "Modern and Sleek Interior" },
    { src: "./Images/Library(31).jpg", desc: "Library with a Contemporary Touch" },
    { src: "./Images/Library(32).jpg", desc: "Large Open Spaces for Reading" }
  ];
  