export const imageSources = [
    { src: "./Images/Library(3).jpg", desc: "Explore Snacks." },
    { src: "./Images/Library(4).jpg", desc: "Explore the wonders of space in our Cafeteria" },
    { src: "./Images/Library(6).jpg", desc: "Space vibes to elevate your cafeteria visit" },
    { src: "./Images/Library(8).jpg", desc: "Take a break and explore the beauty of space" },
    { src: "./Images/Library(9).jpg", desc: "Cafeteria!" },
    { src: "./Images/Library(10).jpg", desc: "Cafeteria!" },
    { src: "./Images/Library(12).jpg", desc: "Cafeteria!" },
    { src: "./Images/Library(13).jpg", desc: "Cafeteria!" },
    { src: "./Images/Library(15).jpg", desc: "Comfortable Seating" },
    { src: "./Images/Library(16).jpg", desc: "Modern Furniture and Style" },
    { src: "./Images/Library(18).jpg", desc: "Inspiring Library View" },
    { src: "./Images/Library(21).jpg", desc: "Keep your belongings safe with our lockers. 🔒" },
    { src: "./Images/Library(22).jpg", desc: "Bright and Open Layout" },
    { src: "./Images/Library(24).jpg", desc: "Calm and Inviting Ambiance" },
    { src: "./Images/Library(25).jpg", desc: "Perfect for Studying and Reading" },
    { src: "./Images/Library(26).jpg", desc: "Stay updated with the latest news and trends" },
    { src: "./Images/Library(27).jpg", desc: "Enjoy a Fresh air, with our air purifier. 🌿💧" },
    { src: "./Images/Library(28).jpg", desc: "Relax and breathe easy with our air diffuser. 🌬️💧" },
    { src: "./Images/Library(30).jpg", desc: "Online Mock Exams Setup" },
    { src: "./Images/Library(31).jpg", desc: "Fuel your day with a perfect cup from our coffee machine. ☕✨" },
    { src: "./Images/Library(32).jpg", desc: "Freshly brewed coffee. ☕😊" },
    { src: "./Images/Logo.png", desc: "Swa-Abhyas" }
  ];
  